FROM python:3.10-slim

WORKDIR /bot

RUN apt-get update && apt-get -y install libpq-dev gcc dos2unix && apt-get clean

COPY . .

RUN dos2unix ./entrypoint-bot.sh
RUN chmod +x ./entrypoint-bot.sh
CMD ./entrypoint-bot.sh

EXPOSE 8001
