version: '3'

services:
  mini_dotabuff_pgdb:
    image: postgres
    container_name: mini_dotabuff_pgdb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "1588:5432"
    volumes:
      - mini-dotabuff-pgdata:/var/lib/postgresql/data
    networks:
      dotabuff_network:
        ipv4_address: 172.18.0.20

  mini_dotabuff_django:
    build:
      context: .
      dockerfile: Dockerfile-backend
    platform: linux/amd64
    container_name: minidotabuffdjango
    restart: unless-stopped
    depends_on:
      - mini_dotabuff_pgdb
    tty: true
    env_file:
      - .env
    ports:
      - "1688:8000"
    networks:
      dotabuff_network:
        ipv4_address: 172.18.0.21

  mini_dotabuff_bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    platform: linux/amd64
    container_name: mini_dotabuff_bot
    restart: unless-stopped
    depends_on:
      - mini_dotabuff_django
    tty: true
    env_file:
      - .env
    networks:
      dotabuff_network:
        ipv4_address: 172.18.0.22


networks:
  dotabuff_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

volumes:
  mini-dotabuff-pgdata:
