# Generated by Django 4.2.3 on 2023-08-16 18:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_id",
                    models.IntegerField(help_text="ID of the game.", unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the user.", max_length=63),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsersGames",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        help_text="Nickname of the player in this game.", max_length=63
                    ),
                ),
                (
                    "hero",
                    models.CharField(
                        help_text="The hero the player played on.", max_length=63
                    ),
                ),
                (
                    "kills",
                    models.IntegerField(
                        help_text="The number of kills made by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "deaths",
                    models.IntegerField(
                        help_text="The number of deaths by player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "assists",
                    models.IntegerField(
                        help_text="The number of assists by playere.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "networth",
                    models.IntegerField(
                        help_text="The amount of gold earned by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "last_hits",
                    models.IntegerField(
                        help_text="The number of last hits creeps by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "denies",
                    models.IntegerField(
                        help_text="The number of denied creeps by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "gpm",
                    models.IntegerField(
                        help_text="The amount of gold per minute earned by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "xpm",
                    models.IntegerField(
                        help_text="The amount of experience per minute earned by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "damage",
                    models.IntegerField(
                        help_text="The amount of damage dealt by the player.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="core.game",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="core.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="games",
            field=models.ManyToManyField(through="core.UsersGames", to="core.game"),
        ),
    ]
