# Generated by Django 4.2.3 on 2023-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_telegramprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dotabuff_id",
            field=models.IntegerField(
                help_text="ID of the user on dotabuff.", unique=True
            ),
            preserve_default=False,
        ),
    ]
